---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: autocomplete
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 80
    name: app-port
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
    name: backend-port
  type: LoadBalancer
...