---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: autocomplete
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: autocomplete
        tier: frontend
    spec:
      containers:
        - name: autocomplete-frontend-container
          image: "public.ecr.aws/s3c9p0p7/autocomplete-frontend:0.1"
...