---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: autocomplete
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: autocomplete
        tier: backend
    spec:
      containers:
        - name: autocomplete-backend-container
          image: "public.ecr.aws/s3c9p0p7/autocomplete-backend:0.1"
          ports:
            - name: http
              containerPort: 80
...